version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: elevatr
      POSTGRES_PASSWORD: elevatr
      POSTGRES_DB: elevatr_dev
    ports:
      - "5433:5432"
    volumes:
      - elevatr_db_data:/var/lib/postgresql/data

volumes:
  elevatr_db_data:
