# Generated by Django 5.2.3 on 2025-06-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recruiter_phone_number_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='studied_at',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studied_at',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
